package cmd

import (
	"fmt"
	"os"
	"path/filepath"
	"krokis/internal/config"

	"github.com/spf13/cobra"
)

var initCmd = &cobra.Command{
	Use:   "init",
	Short: "Initialize Krokis project structure and scaffolding",
	Long:  `Creates the .krokis folder, default configurations, wiki templates, and scaffolds workspace Agent Skills.`,
	Run: func(cmd *cobra.Command, args []string) {
		// 1. Verify git repo
		if _, err := os.Stat(".git"); os.IsNotExist(err) {
			fmt.Println("Error: No .git directory found. Please run 'git init' first.")
			os.Exit(1)
		}

		fmt.Println("Initializing Krokis project structure...")

		// 2. Load and write config
		cfg := config.Default()
		if err := config.Save(cfg); err != nil {
			fmt.Printf("Error creating config file: %v\n", err)
			os.Exit(1)
		}
		fmt.Println("✓ Created .krokis/config.toml")

		// 3. Create wiki dir & templates
		wikiDir := cfg.Wiki.Directory
		if err := os.MkdirAll(wikiDir, 0755); err != nil {
			fmt.Printf("Error creating wiki directory: %v\n", err)
			os.Exit(1)
		}
		
		scaffoldWikiTemplates(wikiDir)
		fmt.Printf("✓ Scaffolded wiki templates in %s/\n", wikiDir)

		// 4. Scaffold Agent Skills
		activeAgentDir := getActiveAgentSkillsDir()
		if err := scaffoldAgentSkills(activeAgentDir); err != nil {
			fmt.Printf("Error scaffolding agent skills: %v\n", err)
			os.Exit(1)
		}
		fmt.Printf("✓ Scaffolded Krokis skills in %s/\n", activeAgentDir)

		fmt.Println("\nKrokis Initialized Successfully! Run 'krokis serve' to open the dashboard.")
	},
}

func init() {
	rootCmd.AddCommand(initCmd)
}

func scaffoldWikiTemplates(wikiDir string) {
	templates := map[string]string{
		"ARCHITECTURE.mdx": `---
title: System Architecture
author: Krokis CLI
---

# Architecture Overview

Use this file to map out your high-level component diagrams, system bounds, and module layouts.

<InfoBox type="info">
  This is a template generated by Krokis init. Update it to match your target system.
</InfoBox>

## System Flow
<ArchitectureGraph />
`,
		"DESIGN_DECISIONS.mdx": `---
title: Design Decisions (ADRs)
author: Krokis CLI
---

# Architectural Decision Records (ADRs)

Document critical architectural decisions here.

### ADR 001: Standardized Specs
- **Status**: Approved
- **Context**: Code quality and agent alignment.
- **Decision**: We use OpenSpec for all feature implementations.
- **Consequences**: Structured specification folder, deterministic agent instructions.
`,
		"DEPENDENCY_MAP.mdx": `---
title: Dependency Map
author: Krokis CLI
---

# System Dependencies

Maintain a clear map of external APIs, microservices, and client boundaries.

<InfoBox type="tip">
  Keep this document up-to-date as dependencies change, so agents remain aware of system limits.
</InfoBox>
`,
	}

	for filename, content := range templates {
		path := filepath.Join(wikiDir, filename)
		if _, err := os.Stat(path); os.IsNotExist(err) {
			_ = os.WriteFile(path, []byte(content), 0644)
		}
	}
}

func getActiveAgentSkillsDir() string {
	// Look for existing .agent or .agents
	if _, err := os.Stat(".agent"); err == nil {
		return ".agent/skills"
	}
	if _, err := os.Stat(".agents"); err == nil {
		return ".agents/skills"
	}
	// Default to standard .agents
	return ".agents/skills"
}

func scaffoldAgentSkills(skillsRoot string) error {
	skills := map[string]map[string]string{
		"krokis-insights": {
			"SKILL.md": `---
name: krokis-insights
description: Analyzes git cadence, metrics, and project quality reports.
---
# Krokis Insights Skill
This skill executes the krokis telemetry collection.

## Usage
Run the following command to update telemetry:
` + "```bash" + `
krokis insights
` + "```" + `
`,
		},
		"krokis-wiki": {
			"SKILL.md": `---
name: krokis-wiki
description: Scaffolds or syncs SNAKE_CASE wiki articles in MDX.
---
# Krokis Wiki Skill
This skill helps agents document system architecture.

## Usage
Run the following command to create a new wiki document:
` + "```bash" + `
krokis wiki create <NAME>
` + "```" + `
`,
		},
	}

	for skillName, files := range skills {
		skillDir := filepath.Join(skillsRoot, skillName)
		if err := os.MkdirAll(skillDir, 0755); err != nil {
			return err
		}
		for filename, content := range files {
			filePath := filepath.Join(skillDir, filename)
			if _, err := os.Stat(filePath); os.IsNotExist(err) {
				if err := os.WriteFile(filePath, []byte(content), 0644); err != nil {
					return err
				}
			}
		}
	}
	return nil
}
