package cmd

import (
	"fmt"
	"os"
	"path/filepath"
	"krokis/internal/config"
	"krokis/internal/wiki"

	"github.com/spf13/cobra"
)

var initCmd = &cobra.Command{
	Use:   "init",
	Short: "Initialize Krokis project structure and scaffolding",
	Long:  `Creates the .krokis folder, default configurations, wiki templates, and scaffolds workspace Agent Skills.`,
	Run: func(cmd *cobra.Command, args []string) {
		// 1. Verify git repo
		if _, err := os.Stat(".git"); os.IsNotExist(err) {
			fmt.Println("Error: No .git directory found. Please run 'git init' first.")
			os.Exit(1)
		}

		fmt.Println("Initializing Krokis project structure...")

		// 2. Load and write config
		cfg := config.Default()
		if err := config.Save(cfg); err != nil {
			fmt.Printf("Error creating config file: %v\n", err)
			os.Exit(1)
		}
		fmt.Println("✓ Created .krokis/config.toml")

		// 3. Create wiki dir & templates
		wikiDir := cfg.Wiki.Directory
		if err := os.MkdirAll(wikiDir, 0755); err != nil {
			fmt.Printf("Error creating wiki directory: %v\n", err)
			os.Exit(1)
		}
		
		scaffoldWikiTemplates(wikiDir)
		fmt.Printf("✓ Scaffolded wiki templates in %s/\n", wikiDir)

		// 4. Scaffold Agent Skills
		activeAgentDir := getActiveAgentSkillsDir()
		if err := scaffoldAgentSkills(activeAgentDir); err != nil {
			fmt.Printf("Error scaffolding agent skills: %v\n", err)
			os.Exit(1)
		}
		fmt.Printf("✓ Scaffolded Krokis skills in %s/\n", activeAgentDir)

		// 5. Scaffold sample openapi.yaml
		openapiPath := cfg.Insights.OpenAPI
		if openapiPath == "" {
			openapiPath = "openapi.yaml"
		}
		if err := scaffoldOpenAPISpec(openapiPath); err != nil {
			fmt.Printf("Error scaffolding openapi.yaml: %v\n", err)
			os.Exit(1)
		}
		fmt.Printf("✓ Scaffolded sample OpenAPI spec in %s\n", openapiPath)

		// 6. Build initial Wiki Index
		if err := wiki.BuildIndex(cfg.Wiki.Directory); err != nil {
			fmt.Printf("Warning: Failed to create wiki index on init: %v\n", err)
		} else {
			fmt.Println("✓ Scaffolded wiki index WIKI_INDEX.mdx")
		}

		fmt.Println("\nKrokis Initialized Successfully! Run 'krokis serve' to open the dashboard.")
	},
}

func init() {
	rootCmd.AddCommand(initCmd)
}

func scaffoldWikiTemplates(wikiDir string) {
	templates := map[string]string{
		"ARCHITECTURE.mdx": `---
title: System Architecture
author: Krokis CLI
---

# Architecture Overview

Use this file to map out your high-level component diagrams, system bounds, and module layouts.

<InfoBox type="info">
  This is a template generated by Krokis init. Update it to match your target system.
</InfoBox>

## System Flow
<ArchitectureGraph />
`,
		"DESIGN_DECISIONS.mdx": `---
title: Design Decisions (ADRs)
author: Krokis CLI
---

# Architectural Decision Records (ADRs)

Document critical architectural decisions here.

### ADR 001: Standardized Specs
- **Status**: Approved
- **Context**: Code quality and agent alignment.
- **Decision**: We use OpenSpec for all feature implementations.
- **Consequences**: Structured specification folder, deterministic agent instructions.
`,
		"DEPENDENCY_MAP.mdx": `---
title: Dependency Map
author: Krokis CLI
---

# System Dependencies

Maintain a clear map of external APIs, microservices, and client boundaries.

<InfoBox type="tip">
  Keep this document up-to-date as dependencies change, so agents remain aware of system limits.
</InfoBox>
`,
		"USER_MANUAL.mdx": `---
title: Krokis User Guide
author: Krokis CLI
---

# Krokis User Manual

Welcome to the interactive project dashboard! Krokis helps agents maintain OpenSpec workflows and humans audit project health.

## Core Commands

You can run these commands directly in your terminal:

- **Scaffold**: <code>krokis init</code> setups folders, configs, and Agent Skills.
- **Insights**: <code>krokis insights</code> scans Git cadence and QA metrics reports.
- **Diagnostics**: <code>krokis doctor</code> audits repository layout and setup health.
- **Validate**: <code>krokis validate</code> verifies configuration file correctness.
- **Serve**: <code>krokis serve</code> launches this local visual dashboard.

## Interactive Widgets Showcase

Here are some custom components you can embed inside any .mdx wiki file in .krokis/wiki/:

### 1. Info Callouts (InfoBox)

Use <code>&lt;InfoBox type="tip" title="..."&gt;Your message&lt;/InfoBox&gt;</code> to document tips:

<InfoBox type="tip" title="Best Practice">
  Always run <code>krokis validate</code> after editing configuration parameters!
</InfoBox>

Support types include: <code>info</code>, <code>tip</code>, <code>warning</code>, and <code>caution</code>.

### 2. Telemetry KPI Cards (MetricsCard)

Use <code>&lt;MetricsCard value="..." label="..." /&gt;</code> to draw focus to a metric:

<MetricsCard value="100%" label="Code Quality Score" />

### 3. Embed Dynamic Reports

You can also embed the complete project health and git cadence widgets directly inside any wiki article:

#### Git Cadence Graph (&lt;TaskCadence /&gt;):
<TaskCadence />

#### Unit Test Summary (&lt;TestResults /&gt;):
<TestResults />
`,
	}

	for filename, content := range templates {
		path := filepath.Join(wikiDir, filename)
		if _, err := os.Stat(path); os.IsNotExist(err) {
			_ = os.WriteFile(path, []byte(content), 0644)
		}
	}
}

func getActiveAgentSkillsDir() string {
	// Look for existing .agents or .agent
	if _, err := os.Stat(".agents"); err == nil {
		return ".agents/skills"
	}
	if _, err := os.Stat(".agent"); err == nil {
		return ".agent/skills"
	}
	// Default to standard .agents
	return ".agents/skills"
}

func scaffoldAgentSkills(skillsRoot string) error {
	skills := map[string]map[string]string{
		"krokis-insights": {
			"SKILL.md": `---
name: krokis-insights
description: Analyzes git cadence, metrics, and project quality reports.
---
# Krokis Insights Skill
This skill executes the krokis telemetry collection.

## Usage
Run the following command to update telemetry:
` + "```bash" + `
krokis insights
` + "```" + `
`,
		},
		"krokis-wiki": {
			"SKILL.md": `---
name: krokis-wiki
description: Scaffolds or syncs SNAKE_CASE wiki articles in MDX.
---
# Krokis Wiki Skill
This skill helps agents document system architecture.

## Usage
Run the following command to create a new wiki document:
` + "```bash" + `
krokis wiki create <NAME>
` + "```" + `
`,
		},
		"roadmap-coordination": {
			"SKILL.md": `---
name: roadmap-coordination
description: Maintain the project's global ROADMAP.md using the Now, Queued, Exploring, and Parked horizons. Use when prioritizing future product directions, recording deferred ideas, promoting an idea toward an OpenSpec change, or reviewing roadmap scope against PRODUCT.md and active changes.
---
# Roadmap Coordination Skill
Helps agents maintain commitment-based product development horizons.

## Horizons
- **Now**: current focus. Link to active OpenSpec change.
- **Queued**: committed next work with clear scope.
- **Exploring**: plausible ideas needing validation or user check-in.
- **Parked**: passive idea bank.
`,
		},
	}

	for skillName, files := range skills {
		skillDir := filepath.Join(skillsRoot, skillName)
		if err := os.MkdirAll(skillDir, 0755); err != nil {
			return err
		}
		for filename, content := range files {
			filePath := filepath.Join(skillDir, filename)
			if _, err := os.Stat(filePath); os.IsNotExist(err) {
				if err := os.WriteFile(filePath, []byte(content), 0644); err != nil {
					return err
				}
			}
		}
	}
	return nil
}

func scaffoldOpenAPISpec(path string) error {
	if _, err := os.Stat(path); err == nil {
		return nil // already exists
	}

	content := `openapi: 3.0.3
info:
  title: Krokis Sample API
  description: This is a placeholder OpenAPI spec scaffolded by Krokis init.
  version: 1.0.0
paths:
  /api/insights:
    get:
      summary: Retrieve project health metrics
      responses:
        '200':
          description: A telemetry dataset in JSON format
  /api/wiki:
    get:
      summary: Retrieve list of MDX wiki articles
      responses:
        '200':
          description: A list of wiki filename strings
`
	return os.WriteFile(path, []byte(content), 0644)
}
